[package]
name = "codegenta"
version = "0.0.1"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A model code generator from database table using rustorm ORM"
readme = "README.md"
repository = "https://github.com/ivanceras/codegenta"
documentation = "https://ivanceras.github.io/codegenta/codegenta/"

[lib]
name = "codegenta"

#[dependencies.rustorm]
#path = "../rustorm"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[dependencies]
rustc-serialize = "*"
uuid = "*"
time = "*"
rustorm ="*"
