[package]
name = "codegenta"
version = "0.0.3"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A model code generator from database table using rustorm ORM"
readme = "README.md"
repository = "https://github.com/ivanceras/codegenta"
documentation = "https://ivanceras.github.io/codegenta/codegenta/"
keywords = ["orm", "codegen", "generator", "database"]

[lib]
name = "codegenta"


#[dependencies.rustorm]
#git = "https://github.com/ivanceras/rustorm.git"


#[dependencies.rustorm]
#path = "../rustorm"
#features = ["sqlite"]

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[dependencies]
rustc-serialize = "*"
uuid = "*"
time = "*"



[dependencies.rustorm]
version = "0.1.3"
features = ["sqlite"]
